version: "3"
services:
  redis-server:
    image: "redis"
    ports:
      - "6379:6379"

  api-node-redis:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app

volumes:
  cache:
    driver: local
