version: "3"
services:
  consumer-api:
    working_dir: /app
    stdin_open: true
    build:
      context: .
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules/
    tty: true
