version: "3"
services:
  consumer-api:
    container_name: front
    working_dir: /app
    stdin_open: true
    build:
      context: .
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules/
    tty: true
    networks:
      - my-proxy-net
    external_links:
      - api:api

networks:
  my-proxy-net:
    external:
      name: giveItANamePlease
